language: node_js
node_js:
  - 16.3.0
cache: yarn

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - yarn build
  - yarn gh-pages

deploy:
  - provider: releases
    skip_cleanup: true
    draft: true
    api_key: $GITHUB_TOKEN
    file:
      - "dist/vue-it-bigger.min.css"
      - "dist/vue-it-bigger.min.js"
      - "dist/vue-it-bigger.min.js.map"
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: gh-pages
    on:
      branch: master
